/* ==========================================================================
   AI Hook Generator — Hook Template Bank
   160 curated opening-line templates across 8 categories. The analysis
   engine scores an uploaded clip and pulls a weighted, de-duplicated
   selection of 20 into the working library. Every line is fully editable
   once it lands in the app.
   ========================================================================== */

const HOOK_BANK = {
  curiosity: [
    "Wait for it… this is not what you think it is.",
    "Nobody's talking about this, and I don't understand why.",
    "I almost didn't post this. Watch until the end.",
    "This took me three tries to get right. Here's why.",
    "You've been doing this wrong the whole time.",
    "Here's the part nobody shows you.",
    "I wasn't going to say anything, but…",
    "Something weird happens at 0:07. Keep watching.",
    "This changed how I see everything.",
    "I didn't believe it either, until this happened.",
    "The internet is sleeping on this and it's criminal.",
    "There's a detail here most people miss completely.",
    "This shouldn't have worked. It did.",
    "I have so many questions after filming this.",
    "You're going to want to rewatch this one.",
    "This is the video I wish someone sent me first.",
    "Okay but why does no one know about this?",
    "I still think about this moment daily.",
    "This is either genius or a huge mistake. You decide.",
    "Three seconds in, everything changes."
  ],

  emotional: [
    "This is for anyone who needed to hear it today.",
    "I wasn't ready for how this would make me feel.",
    "If you know, you know. This one's heavy.",
    "I filmed this through tears, honestly.",
    "This is the moment that changed everything for me.",
    "Some days this is the only thing that gets me through.",
    "I promised myself I'd share this eventually.",
    "This is my letter to the version of me that almost gave up.",
    "Nobody prepares you for a moment like this.",
    "I've never told anyone this before.",
    "This hit different once I understood the whole story.",
    "For every person who's felt invisible lately — this is for you.",
    "I still get emotional watching this back.",
    "This is what healing actually looks like, no filter.",
    "If this doesn't move you, check your pulse.",
    "I made this for the people who feel alone right now.",
    "This is the hardest thing I've ever had to share.",
    "Watch this if you need a reminder that it gets better.",
    "This moment lasted four seconds and changed my whole year.",
    "I wasn't going to cry on camera, but here we are."
  ],

  music: [
    "This beat drop lives in my head rent free.",
    "Turn your volume up. Trust me on this one.",
    "I've had this song on repeat for a week straight.",
    "This is the sound of my whole summer.",
    "Wait for the beat switch — it's everything.",
    "New sound just dropped and it's already a problem.",
    "This melody is going to be stuck in your head by tonight.",
    "If you love this sound, the full track is worth your time.",
    "This is what a perfect drop is supposed to feel like.",
    "I've never skipped this song once, not once.",
    "The bass in this hits completely different with headphones.",
    "This is your sign to make this your next favorite song.",
    "I found the song of the year and nobody's ready.",
    "This track deserves way more plays than it's getting.",
    "The way this beat syncs up here is not a coincidence.",
    "This sound is about to be everywhere. Screenshot this.",
    "I built this whole video around four seconds of sound.",
    "This is the loop that made me stop scrolling.",
    "If this doesn't get you moving, nothing will.",
    "This song deserved a bigger moment than this, but here we go."
  ],

  storytelling: [
    "So this actually happened, and it started completely normal.",
    "Let me tell you about the worst best day of my life.",
    "It was supposed to be a quiet Tuesday. It was not.",
    "Three weeks ago, I made a decision that changed everything.",
    "This story starts with me being way too confident.",
    "Nobody believes this story until I show them proof.",
    "I need to tell someone about this before I forget the details.",
    "This is the story my friends make me repeat constantly.",
    "It all started with one text message I shouldn't have sent.",
    "I promise this story gets so much worse before it gets better.",
    "Picture this: it's 2am, and I make the worst decision of my life.",
    "This is the story of how one small choice snowballed completely.",
    "You need context for this one, so stay with me.",
    "This story has a twist I still can't explain.",
    "I've told this story a hundred times and it never gets old.",
    "It began as a joke. It did not end as a joke.",
    "This is the day my plans fell apart in the best way.",
    "I wasn't planning on sharing this, but it's too good not to.",
    "Everything was fine until exactly this moment.",
    "This is the story that made my whole family go silent."
  ],

  funny: [
    "I did not think this through, and it shows.",
    "This is a public service announcement about my poor decisions.",
    "Someone needs to take my phone away from me.",
    "This is what happens when I'm left unsupervised.",
    "I'm not okay, but at least this is funny.",
    "This is either the best idea I've had or the worst. No in between.",
    "I laughed so hard filming this I nearly cried.",
    "This is why I'm not allowed to plan things anymore.",
    "My family is going to disown me for posting this.",
    "This went so much worse than expected, in the best way.",
    "I need everyone to see what I just did to myself.",
    "This is a cry for help disguised as content.",
    "I tried it so you don't have to. You're welcome.",
    "Nobody asked for this, and yet here we are.",
    "This is the most unserious thing I've filmed all year.",
    "I would like to formally apologize in advance.",
    "This is what confidence with zero skill looks like.",
    "My therapist is going to hear about this one.",
    "I have never been more wrong about anything in my life.",
    "This is the chaos you didn't know you needed today."
  ],

  suspense: [
    "Keep watching. It gets worse before it gets better.",
    "I had thirty seconds to make this decision.",
    "Something was very wrong, and I didn't notice until now.",
    "This is the moment I realized I'd made a huge mistake.",
    "I didn't see what was coming, but you will.",
    "Everything was calm right up until this exact second.",
    "I need you to watch this without looking away.",
    "This is the part where everything goes sideways.",
    "There was no warning before this happened.",
    "I still get chills watching this back.",
    "This was the last normal moment before everything changed.",
    "I had no idea I was being filmed for this.",
    "Watch the background. Something isn't right.",
    "This is the closest call I've ever had, on camera.",
    "I only had one shot to get this right.",
    "This is the exact moment it all clicked into place.",
    "Nobody in this video knew what was about to happen.",
    "I've replayed this a hundred times and it still shocks me.",
    "This was supposed to be routine. It was not.",
    "Hold on, because this takes a turn fast."
  ],

  challenge: [
    "I gave myself 24 hours to pull this off.",
    "This challenge broke me in the best possible way.",
    "I bet you can't do this without flinching.",
    "Day one of trying this until I actually get it right.",
    "This looked easy. It was not easy.",
    "I attempted the thing everyone said was impossible.",
    "This challenge has a 90 percent fail rate. I tried anyway.",
    "I have one week to make this work. Clock's running.",
    "This is my last attempt before I officially give up.",
    "I said yes before I understood what I was agreeing to.",
    "This is the challenge that humbled me completely.",
    "I'm not stopping until I land this.",
    "This took way more attempts than I want to admit.",
    "I dare you to try this and not react.",
    "This is what happens when I refuse to quit.",
    "I gave myself zero excuses and one deadline.",
    "This challenge nearly ended in disaster. Watch.",
    "I'm doing this until it finally works. Attempt number one.",
    "This is harder than it looks, I promise you that.",
    "Somebody had to try this first. It was me."
  ],

  motivation: [
    "Nobody is coming to save you. Get up anyway.",
    "This is your sign to stop waiting for permission.",
    "A year ago I couldn't do this. Watch me now.",
    "You don't need to feel ready to start today.",
    "This is what showing up every single day looks like.",
    "I almost quit right before this moment.",
    "Discipline looked like this when nobody was watching.",
    "This is proof that consistency beats motivation every time.",
    "You are one decision away from a completely different life.",
    "I stopped waiting for the perfect moment and just started.",
    "This is what it looks like to bet on yourself.",
    "Nobody believed this was possible, including me.",
    "This is the version of you that's still worth becoming.",
    "Small steps got me here. They can get you there too.",
    "I built this from nothing, one uncomfortable day at a time.",
    "Stop scrolling and go do the thing you've been avoiding.",
    "This is what happens when you refuse to stay comfortable.",
    "You don't need more time. You need to start now.",
    "This is your reminder that it's never too late to begin.",
    "I did this so you'd believe you can too."
  ]
};

// Human-readable metadata used for badges, filters, and the analysis legend.
const HOOK_CATEGORIES = [
  { id: "curiosity",   label: "Curiosity",       color: "#5CC9F5" },
  { id: "emotional",   label: "Emotional",       color: "#FF6FA0" },
  { id: "music",       label: "Music Promotion", color: "#B98BFF" },
  { id: "storytelling",label: "Storytelling",    color: "#F4C61A" },
  { id: "funny",       label: "Funny",           color: "#7EE08A" },
  { id: "suspense",    label: "Suspense",        color: "#FF4D3D" },
  { id: "challenge",   label: "Challenge",       color: "#FF9C4A" },
  { id: "motivation",  label: "Motivation",      color: "#3DDC97" }
];
